scrape_configs:
  - job_name: 'spring'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    # 采集服务的地址，设置成Springboot应用所在服务器的具体地址
    static_configs:
      - targets: ['192.168.56.1:8080']
